version: 1
formatters:
  basic:
    format: "%(asctime)s | %(levelname)s | %(name)s | %(message)s"
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: basic
    stream: ext://sys.stdout
root:
    level: INFO
    handlers: [console]
